# Generated by Django 3.2.7 on 2021-10-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211019_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_status',
            new_name='order',
        ),
    ]
